
title: "Windows Server Talks"
description: "DFS, Active Directory, Hyper-V, and PowerShell Guides by Mohit Maurya"

theme: jekyll-theme-cayman

# Mandatory for GitHub Pages
permalink: pretty
url: "https://mauryamohit07.github.io"
baseurl: "/WindowsServerTalks"

markdown: GFM

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# This is important for GitHub Pages
collections:
  docs:
    output: true

# Navbar links FIXED â€” must point to .html pages Jekyll generates
navbar:
  - name: "Home"
    link: "/WindowsServerTalks/"
  - name: "DFS Backup"
    link: "/WindowsServerTalks/domain-based-dfs-n-auto-backup.html"
  - name: "DFS Link Recovery"
    link: "/WindowsServerTalks/recover-deleted-dfs-n-links.html"
